server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://admin:admin123@localhost:27017/
        database: user
        auto-index-creation: true

application-version: 1.0