
CREATE TABLE animal (
    id INT AUTO_INCREMENT NOT NULL,
    NOME_PROVISORIO VARCHAR(255) NOT NULL,
    IDADE_ESTIMADA INTEGER NOT NULL,
    TIPO_ANIMAL VARCHAR(255) NOT NULL,
    RACA VARCHAR(255) NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_ADOCAO DATE,
    CONDICAOES_CHEGADA VARCHAR(255) NOT NULL,
    NOME_RECEBEDOR VARCHAR(255) NOT NULL,
    DATA_OBITO DATE,
    PORTE VARCHAR(255) NOT NULL,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);
